### ISSUE TITLE
Icon Consistency

### ISSUE THREAD

**Issue by jmacato** [zkSNACKs/WasabiDesign#3]
Since we have adopted a Visual Studio-style User Interface, it is imperative that we have to sort out our Icon Design Language to be more inline with the guidelines as shown here:
https://docs.microsoft.com/en-us/visualstudio/extensibility/ux-guidelines/images-and-icons-for-visual-studio?view=vs-2019

**Comment by molnard** [comment]
If we are planning to use design guidelines: https://github.com/zkSNACKs/WasabiDesign/issues/6
We will have icons like this:  https://material.io/resources/icons/?style=baseline

**Comment by jmacato** [comment]
For reference: Comparisons of VS's handling of Solution Explorer Icons

Light Theme, 9pt font size:
![image](https://user-images.githubusercontent.com/16554748/76194248-bb5aff80-6220-11ea-871e-2a96686510ea.png)

Dark Theme, 9pt:
![image](https://user-images.githubusercontent.com/16554748/76194336-ecd3cb00-6220-11ea-9991-1ee7097b1df6.png)

Light Theme, 15pt: 
![image](https://user-images.githubusercontent.com/16554748/76194592-6f5c8a80-6221-11ea-8c76-0e8578434e78.png)

Dark Theme, 15pt:
![image](https://user-images.githubusercontent.com/16554748/76194549-59e76080-6221-11ea-8917-011a9134471f.png)

Observations:

1. They dont scale the icons with the font, we could do better than that since we use vectorized icons everywhere anyway.

2. The grayscale palette described in the VS Icon design is inverted when it switches to dark mode. Accent colors are ignored.

**Comment by molnard** [comment]
I like it and also that the user will have an option to use light mode.

**Comment by jmacato** [comment]
~https://github.com/AvaloniaUI/Avalonia/issues/3655 prevents us from doing dynamic color change for icons and other controls that are declared inside styles~ 

Seems to be fixed at Avalonia master branch. Though the fix is not backportable so the color/theme change feature may wait until the next major release...

**Comment by jmacato** [comment]
Addressed by https://github.com/zkSNACKs/WalletWasabi/pull/3267 :)
