### ISSUE TITLE
Visualized Wallet UX

### ISSUE THREAD

**Issue by molnard** [zkSNACKs/WasabiDesign#5]
Found here: 
https://github.com/zkSNACKs/Meta/issues/8

https://medium.com/@nopara73/new-bitcoin-wallet-experience-thinking-outside-the-box-845b8a22a7e0

**Comment by BTCparadigm** [comment]
WW2 obsoletes this?

**Comment by molnard** [comment]
I think this whole repo can be closed as it is not used. Asking Dan...

**Comment by molnard** [comment]
Yes.
