### ISSUE TITLE
Change default font to Segoe UI-like OSS fonts.

### ISSUE THREAD

**Issue by jmacato** [zkSNACKs/WasabiDesign#9]
Currently we are using `Ubuntu Sans` on the app and i think it doesn't fit with our UI. I think the most ideal font for a Visual Studio like UI is Segoe UI but unfortunately, that font is proprietary to Microsoft. 

Thereby I propose the following open licensed fonts as an alternative for the default font of the app (ordered by most likeness with Segoe UI):

Reference (Segoe UI):
![image](https://user-images.githubusercontent.com/16554748/77733685-4b32e300-7042-11ea-9f6e-437b13429999.png)

1.) Selawik by Microsoft (tweaked version from this specific dev branch of the font: https://github.com/vv-monsalve/Selawik/tree/QA-Selawik/sources/Glyphs).
![image](https://user-images.githubusercontent.com/16554748/77733255-884aa580-7041-11ea-9168-dce7e2bdc91d.png)

https://github.com/vv-monsalve/Selawik/blob/QA-Selawik/fonts/ttf/Selawik-Regular.ttf

2.) Source Sans Pro by Adobe
![image](https://user-images.githubusercontent.com/16554748/77733583-16bf2700-7042-11ea-9141-1a91f085ee34.png)

https://fonts.google.com/specimen/Source+Sans+Pro

3.) Lato:
![image](https://user-images.githubusercontent.com/16554748/77733389-c21bac00-7041-11ea-9762-f1477299febe.png)

https://fonts.google.com/specimen/Lato

**Comment by ghost** [comment]
I personally like monospace fonts. 
But am open for anything, not really a contentious point for me.

**Comment by jmacato** [comment]
@MaxHillebrand well, we're already using monospace for the important stuff :) This is for the general look of the app. And since we're using Visual Studio as a reference for the overall theme, it's good to have wasabi more or less inline with it

**Comment by jmacato** [comment]
Obsoleted by the new Fluent Design using [Inter](https://rsms.me/inter/)
